# Generated by Django 4.1.4 on 2023-01-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'camion',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=45)),
                ('fecha_alta', models.DateTimeField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contenedor',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea1', models.CharField(max_length=200)),
                ('linea2', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo_postal', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('provincia', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.cliente')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nss', models.CharField(max_length=45, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.departamento')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='EstadoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_item',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_pedido',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('alto', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('fecha_alta', models.DateField()),
                ('preferencias', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.color')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.contenedor')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.empleado')),
                ('estado_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.estadoitem')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemsLotes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.item')),
            ],
            options={
                'db_table': 'items_lotes',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.empleado')),
                ('items', models.ManyToManyField(through='furnipop_api.ItemsLotes', to='furnipop_api.item')),
            ],
            options={
                'db_table': 'lote',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.cliente')),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=45)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.camion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.cliente')),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.direccion')),
                ('estado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.estadopedido')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.metodopago')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('fecha_caducidad', models.CharField(max_length=45)),
                ('cvv', models.CharField(max_length=45)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.metodopago')),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=45, unique=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.metodopago')),
            ],
            options={
                'db_table': 'paypal',
            },
        ),
        migrations.AddField(
            model_name='itemslotes',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.lote'),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.material'),
        ),
        migrations.AlterUniqueTogether(
            name='itemslotes',
            unique_together={('lote', 'item')},
        ),
        migrations.CreateModel(
            name='LotesPedidos',
            fields=[
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='furnipop_api.lote')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.pedido')),
            ],
            options={
                'db_table': 'lotes_pedidos',
                'unique_together': {('lote', 'pedido')},
            },
        ),
        migrations.CreateModel(
            name='ItemsPedidos',
            fields=[
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='furnipop_api.pedido')),
                ('cantidad', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.item')),
            ],
            options={
                'db_table': 'items_pedidos',
                'unique_together': {('pedido', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ImagenesItems',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='furnipop_api.item')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.imagen')),
            ],
            options={
                'db_table': 'imagenes_items',
                'unique_together': {('item', 'imagen')},
            },
        ),
    ]
