# Generated by Django 4.1.4 on 2023-01-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslotes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
