# Generated by Django 4.1.4 on 2023-01-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0002_alter_itemslotes_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemslotes',
            unique_together=set(),
        ),
    ]
