# Generated by Django 4.1.4 on 2023-01-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0005_alter_itemslotes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='email',
            field=models.EmailField(max_length=45, unique=True),
        ),
    ]
