# Generated by Django 4.1.4 on 2023-01-18 16:40

from django.db import migrations, models
import furnipop_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0006_remove_metodopago_nombre_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='src',
            field=models.ImageField(blank=True, upload_to=furnipop_api.models.upload_to),
        ),
    ]
