# Generated by Django 4.1.4 on 2023-01-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0008_imagen_item_alter_imagen_src_delete_imagenesitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnipop_api.item'),
        ),
    ]
