# Generated by Django 4.1.4 on 2023-02-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0010_pedido_items_pedido_lotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspedidos',
            name='idA',
            field=models.IntegerField(db_column='idA', null=True),
        ),
        migrations.AddField(
            model_name='lotespedidos',
            name='idA',
            field=models.IntegerField(db_column='idA', null=True),
        ),
    ]
