# Generated by Django 4.1.4 on 2023-02-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0028_alter_lotespedidos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspedidos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
