# Generated by Django 4.1.4 on 2023-02-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0030_alter_lotespedidos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspedidos',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.pedido'),
        ),
        migrations.AlterField(
            model_name='lotespedidos',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='furnipop_api.lote'),
        ),
    ]
