# Generated by Django 4.1.4 on 2023-03-08 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnipop_api', '0032_cliente_favoritos_pedido_items_pedido_lotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_alta',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 12, 1, 25, 812176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_alta',
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
    ]
